Use latin1 encoding for file lookup and copy module
Since latin1 is a one byte encoding, foo.decode("latin1").encode("latin1") ==
foo holds true. This is not the case for "utf-8". '\xe4' is a latin1 encoded
'ä', '\xc3\xa4' is a utf-8 encoded 'ä':

>>> '\xe4'.decode("utf8").encode("utf8")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 0: unexpected end of data
>>> '\xe4'.decode("latin1").encode("latin1")
'\xe4'
>>> '\xc3\xa4'.decode("latin1").encode("latin1")
'\xc3\xa4'